export const PeiceNames = {
  WALL: "WALL",
  SMALL_TRAP: "SMALL_TRAP",
  LARGE_TRAP: "LARGE_TRAP",
  SMALL_TREASURE: "SMALL_TREASURE",
  LARGE_TREASURE: "LARGE_TREASURE",
  SMALL_POWERUP: "SMALL_POWERUP",
  LARGE_POWERUP: "LARGE_POWERUP",
};

export const PieceStringSymbols = {
  EMPTY: "A",
  WALL: "B",
  SMALL_TRAP: "C",
  LARGE_TRAP: "D",
  SMALL_TREASURE: "E",
  LARGE_TREASURE: "F",
  SMALL_POWERUP: "G",
  LARGE_POWERUP: "H",
};
