export const PeiceNames = {
  WALL: "WALL",
  SMALL_TRAP: "SMALL_TRAP",
  LARGE_TRAP: "LARGE_TRAP",
  SMALL_TREASURE: "SMALL_TREASURE",
  LARGE_TREASURE: "LARGE_TREASURE",
  SMALL_POWERUP: "SMALL_POWERUP",
  LARGE_POWERUP: "LARGE_POWERUP",
};
